### PR TITLE
Resolves #34. Update python script for Inkscape 1.0, breaks 0.9 support

### LINKED ISSUE #34: update needed for Inkscape version 1.0
Hello,
Thank you for providing this extension for Inkscape users!

This is just to let you know that most 3rd party Inkscape extensions, like this one, probably will not work with the upcoming new Inkscape version, the long-awaited version 1.0.

Here is the info you need to update this extension, so that it will work with 1.0 and future versions.  
https://wiki.inkscape.org/wiki/index.php?title=Updating_your_Extension_for_1.0

If you have further questions, you can contact Inkscape developers via [mailing lists](https://lists.inkscape.org/postorius/lists/?all-lists), [forum](https://inkscape.org/forums/extensions/), or the [chatroom](https://chat.inkscape.org/channel/inkscape_extensions).

If you have already updated it, please disregard this message.

All best,
brynn

### PR DESCRIPTION
**Pull request by UnicodingUnicorn**

### CODE REVIEW

**Comment by lifelike** [comment]
Thank you!

It looks like there are some similarities to what I made on the support_inkscape_1.0, but also some things that are different (and my version did not work, so ...).

It looks like it would not be impossible to make it also work for 0.9?

**Comment by UnicodingUnicorn** [comment]
Yikes, I didn't know you were also working on it, sorry. Inkscape changed the location of some of the functions used, and also changed how the type of the arguments is passed. So unless there is a way of differentiating Inkscape version so different code can be run, I can't think of a way to support both versions with the same script.

**Comment by lifelike** [comment]
My work on 1.0-support failed. Not sure what was wrong. Looks like you did far fewer changes than I did. If it works I will be happy to scrap my branch.

In the past when the API changed it was possible to just look at if some function was present to decide which one to call.

**Comment by UnicodingUnicorn** [comment]
Funnily enough, the code to do it was right above the place I changed stuff.

**Comment by lifelike** [comment]
Merged this and removed the warning from the README about 1.0 not working.

I do not have 1.0 installed yet. It seems like this works with 0.92.3 though. Thanks for sorting that out, UnicodingUnicorn.

**Pull request merged**
