### PR TITLE
Working Upgrade for InkScape 1.0/1.1dev

### PR DESCRIPTION
**Pull request by vmario89**

### CODE REVIEW

**Comment by vmario89** [comment]
sorry i did not see the 1.0 branch from this repo. i didnt look for it because 99% of all inkscape repos dont have another branch :-/ if i find time i can try to merge with yours and yes i dropped the old support. i personally dont like the legacy spaghetti code. nearly nobody in the futue will install the old inkscape version except for severe reasons

**Comment by lifelike** [comment]
The problem is that none of the Linux distributions (or versions of Linux distributions) I have on my computers have updated their Inkscape packages to 1.0. I do not want to rely on Linux users (myself included) to have to rely on software from third-party sources or compile themselves rather than just use natural ways of installing software (e.g. "sudo apt install inkscape"). Of course eventually support for older versions would have to be dropped.

**Comment by lifelike** [comment]
On second thought, let's keep the versions separate. All changes to make Inkscape 1.0 can go into a new release 3.0 or something of those extensions, and everyone (like me) still on old Inkscape can still use the old releases for now. Keeps the spaghetti code away. Just has to get the branches and pull requests figured out.

**Comment by lifelike** [comment]
Changes merged! Thanks vmario89.

I had to clean up some whitespace and fix the automatic tests. I think this PR was a significant improvement. There might
be some minor things to look into like some default values handling to better support using the script from the command-line, but I guess very few do that anyway so it is not a high priority (and the error-messages when not setting a value looks reasonable most of the time too).

**Pull request merged**
